// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace dotnetdev_assessment.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240905084131_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dotnetdev_assessment.Models.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Admin",
                            IsAdmin = true,
                            Name = "Admin Test",
                            PasswordHash = "$2a$11$OYV1f.i2Ery0NzZysd8hZueiMkmRAjIg3MK9aNGD7HGATjhYTjS3m",
                            Position = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Department = "Engineering",
                            IsAdmin = false,
                            Name = "User Test",
                            PasswordHash = "$2a$11$9Yu3vQAmrGzKTSoXWF9jUu.PTSLXFhgOZ4pf2xUZgoiDRixc7IShS",
                            Position = "Engineering",
                            Username = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
